/** Patterns that break the MDX blog engine — used by validator and post-generation cleanup */
export const FORBIDDEN_PATTERNS = {
  jsxComponent: /<[A-Z][a-zA-Z]+[\s/>]/g,
  anchorId: /\{#[^}]+\}/,
  internalAnchorLink: /\[([^\]]+)\]\(#[^)]+\)/,
  scriptTag: /<script[\s>]/i,
  h1InBody: /^# [^#]/m,
  yamlBlockTags: /^tags:\s*\n\s*-/m,
  yamlBlockFaq: /^faq:\s*\n\s*-\s*question/m,
  imageJsx: /<Image[\s/>]/,
  keyTakeaways: /<KeyTakeaways/,
  callout: /<Callout/,
  mockAbsatzFiller: /Absatz \d+ vertieft/i,
  /** SEO_CONTENT_GUIDELINES — investment solicitation / yield claims */
  rentiersYieldClaim: /(?:12\s*[–-]\s*20|12–20|bis\s+zu\s+20)\s*%|\b16\s*%\s*p\.?\s*a\.?/i,
  guaranteedReturn: /garantierte\s+(?:hohe\s+)?rendite|ohne\s+risiko|risk[-\s]?free\s+return|staatlich\s+garantierte\s+(?:rendite|ertrag)/i,
  investCta: /(?:jetzt|heute)\s+(?:anlegen|investieren)|konto\s+eröffnen|mit\s+rentiers(?:\s+pro)?\s+starten|open\s+(?:an\s+)?account|invest\s+(?:now|with\s+rentiers)/i,
  luxcarYield: /luxcar|100\s*%\s*(?:jahreszins|\+|p\.?\s*a\.?)/i,
  fakeExpertAuthor: /dr\.\s*(?:stefan\s+kaufmann|markus\s+hoffmann)|elena\s+(?:marchetti|kowalski)|pierre\s+dijon/i,
  adPolicyEvasion: /facebook\s+financial\s+services\s+policy\s+umgeh|bypass\s+(?:ads?|facebook|google)\s+policy/i,
} as const;

export const FORBIDDEN_PATTERN_MESSAGES: Record<keyof typeof FORBIDDEN_PATTERNS, string> = {
  jsxComponent: 'JSX-Komponenten gefunden — verboten im CMS',
  anchorId: 'Anchor-IDs {#id} gefunden — verboten im CMS',
  internalAnchorLink: 'Interne Anchor-Links [text](#id) gefunden — verboten',
  scriptTag: '<script> Tag gefunden — verboten im CMS',
  h1InBody: 'H1 (# Heading) im Artikelkörper — verboten',
  yamlBlockTags: 'YAML-Block-Array für tags — bitte Inline-Array verwenden',
  yamlBlockFaq: 'YAML-Block-Array für faq — bitte Inline-Array oder List-Syntax im Frontmatter',
  imageJsx: '<Image /> JSX — nur ![alt](url) erlaubt',
  keyTakeaways: '<KeyTakeaways> Komponente — verboten',
  callout: '<Callout> Komponente — verboten',
  mockAbsatzFiller: 'Mock-Kopierpaste (Absatz N vertieft) — Artikel ungültig',
  rentiersYieldClaim: 'Renditeversprechen / %-Claims im Solicitation-Stil — verboten laut SEO_CONTENT_GUIDELINES',
  guaranteedReturn: 'Garantie-Formulierungen für Erträge — verboten',
  investCta: 'Investitions-CTA (anlegen / Konto eröffnen / mit Rentiers starten) — verboten',
  luxcarYield: 'LUXCAR / 100%-Yield-Claims — verboten',
  fakeExpertAuthor: 'Erfundener Experten-Autor — nur Rentiers Redaktion erlaubt',
  adPolicyEvasion: 'Hinweise zum Umgehen von Ad-Policies — verboten',
};
